configured_endpoints: 62
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixedbread%2Fmixedbread-8a9abf45fe3e0db8c9ba59803ff9ef4ce5d0bb780765d3c1a9587dde2a8d6c93.yml
openapi_spec_hash: 0f3af27e4fc27bcbfbb17f0a2c45c060
config_hash: 6fa04d08d4e1a3a45f562e37fab0ea71
