configured_endpoints: 49
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixedbread%2Fmixedbread-6eceba7c701064aa752ff55cf7539a15258dea54c151fec7e56a20c72bc2920a.yml
openapi_spec_hash: 46b9ea8cf4a72ab36be2f5d8fb45de54
config_hash: fef0ea78daf11093ff503919baae5ec0
