configured_endpoints: 51
openapi_spec_url: https://storage.googleapis.com/stainless-sdk-openapi-specs/mixedbread%2Fmixedbread-b1dc7adca94d1a8c12d66e06400ce2f254a7e0ff0036c3817189c68ff1405ece.yml
openapi_spec_hash: dff0a2dc18d54f7f0a8c5be2cfe0aa09
config_hash: fb2cfcdc5ef83ff03407a8b66c26a59b
